services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: counterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    image: 123677443445.dkr.ecr.ap-southeast-2.amazonaws.com/dotnet-counter-api:latest
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=counterdb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: 123677443445.dkr.ecr.ap-southeast-2.amazonaws.com/dotnet-counter-frontend:latest
    ports:
      - "80:80" 
    depends_on:
      - api
      
volumes:
  postgres-data: