name: Build Api
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/CounterApi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build API
        run: dotnet build --no-restore
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

  build-application-image:
    runs-on: ubuntu-latest
    needs: build-api
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build API Docker Image
      run: |
        docker build \
        -t counter-api \
        ./api/CounterApi

  build-frontend-image:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Frontend Docker Image
      run: |
        docker build \
        -t counter-frontend \
        ./frontend