script: |
  cd ~/dotnet-counter-app

  git pull

  aws ecr get-login-password \
    --region ap-southeast-2 \
    | docker login \
      --username AWS \
      --password-stdin \
      123677443445.dkr.ecr.ap-southeast-2.amazonaws.com

  docker compose pull

  docker compose up -d

  docker image prune -f